require("prototypes.items.dormant-seeds")
require("prototypes.items.holmium-items")
require("prototypes.items.lithium-items")
require("prototypes.items.tungsten-items")

require("prototypes.subgroups")
require("prototypes.fluids")
require("prototypes.buildings.space-vent")
require("prototypes.technology")

-- require("prototypes.generation.vgal-saline-fissure")
require("prototypes.generation.vgal-ore")

require("setups.spoilage-setup")
require("setups.weight-setup")

require("prototypes.recipes.space")
require("prototypes.recipes.holmium")
require("prototypes.recipes.tungsten")
require("prototypes.recipes.water-treatment")
require("prototypes.recipes.resources")
require("prototypes.recipes.metal-both")
require("prototypes.recipes.petrochem")
require("prototypes.recipes.chemistry")
require("prototypes.recipes.chemistry-fluorine")
require("prototypes.recipes.water")
require("prototypes.recipes.smelting")
require("prototypes.recipes.bio")
require("prototypes.recipes.atmosphere")
require("prototypes.recipes.voids")
