require("overrides.locale-overrides")
require("overrides.tech-overrides")
require("overrides.overrides")
require("overrides.recipe-overrides")
require("overrides.tech-overrides")
require("overrides.spoilage-overrides")

require("overrides.order-overrides")
require("overrides.icon-overrides")
require("overrides.autoplace-overrides")
require("overrides.factoriopedia-overrides")
