-- vgal.data.extend({
--     {
--         name = "carbon-fiber-rocket-part",
--         prefix = "vgal",
--         technology = "rocket-silo",
--         icons = vgal.icon.register {
--             vgal.icon.get("rocket-part"),
--             vgal.icon.get_in("carbon-fiber")
--         },
--         energy_required = 2,
--         ingredients = {
--             { "rocket-fuel",     1 },
--             { "processing-unit", 1 },
--             { "carbon-fiber",    2 }, -- 
--         },
--         results = {
--             { "rocket-part", 1 }, -- 12800
--         },
--         category = "rocket-building",
--     },
-- }, {
--     groups = { "vgal-rocket-parts" }
-- })
