do
    ---@class agal.Metal:vgal.Metal
    ---@field ore_index integer
    ---@field ore string
    ---@field base_ore string
    ---@field nugget string
    ---@field slag string
    ---@field pebbles string
    ---@field molten string
    ---@field ingot string
    ---@field processed string
    ---@field pellet string
    ---@field roll string
    ---@field angels_plate_recipe_name string
    ---@field ore_states string[]
    ---@field crushed string
    ---@field chunk string
    ---@field crystal string
    ---@field pure string
    ---@field solution string
end
