require("prototypes.vgal-overrides")
require("prototypes.science")
require("prototypes.intermediates.chemical")
require("prototypes.military")
require("prototypes.intermediates.smelting")
require("prototypes.intermediates.circuits")
require("prototypes.intermediates.intermediates")
require("prototypes.buildings.buildings")
